# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit smitte.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
Sys.setenv(TZ = "UTC")
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE,
                      eval = FALSE)
library(simtte)


## ----weibull-example----------------------------------------------------------
library(simtte)
set.seed(42)

lp <- matrix(rnorm(50, mean = 0, sd = 0.5), nrow = 50)

result <- sim_tte(
  pi       = lp,
  mu       = -1,
  coefs    = 1.1,
  time     = seq(0.1, 100, by = 0.1),
  type     = "weibull",
  end_time = 100
)
head(result)


## ----explore-pi---------------------------------------------------------------
data_pi <- explore_pi_tq_surv(
  pi       = seq(-2, 2, by = 0.25),
  mu       = -1,
  shape    = 1.1,
  type     = "weibull",
  end_time = 100
)

plot(survdiff_tq ~ exp(lp), data = data_pi,
     xlab = "Hazard Ratio", ylab = "Survival difference at median",
     log  = "x", type = "l", lwd = 2)
abline(h = 0, v = 1, lty = 2)


## ----ms-builtin---------------------------------------------------------------
data("ms_data")
str(ms_data)


## ----ms-custom----------------------------------------------------------------
library(splines2)

time_new  <- seq(0.1, 24, by = 0.1)
knots_new <- quantile(time_new, probs = c(0.15, 0.35, 0.55, 0.75))

basis_new <- mSpline(time_new, knots = knots_new,
                     Boundary.knots = c(0, 24),
                     degree = 2, intercept = TRUE)
coefs_new <- c(0.05, 0.35, 0.55, 0.30, 0.10, 0.04, 0.02)

n      <- 200
lp_new <- matrix(rep(0, n), nrow = n)

sim_new <- sim_tte(
  pi     = lp_new,
  mu     = -0.5,
  basis  = basis_new,
  coefs  = coefs_new,
  time   = time_new,
  type   = "ms"
)
mean(sim_new$sim_status)


## ----pkpd-model, eval=FALSE---------------------------------------------------
# library(mrgsolve)
# 
# code <- '
# $PARAM CL=2, V=20, KA=1, KIN=1, KOUT=0.5, IC50=1, IMAX=0.9, H0=0.15
# 
# $CMT GUT CENT R
# 
# $INIT p11 = 1
# 
# $OMEGA @labels ECL EV EIC50
# 0.09 0.09 0.16
# 
# $MAIN
# double CLi   = CL * exp(ECL);
# double Vi    = V  * exp(EV);
# double IC50i = IC50 * exp(EIC50);
# R_0 = KIN / KOUT;
# 
# $ODE
# double CP  = CENT / Vi;
# double INH = IMAX * CP / (IC50i + CP);
# double HAZ = H0 * (R / (KIN / KOUT));
# dxdt_GUT  = -KA * GUT;
# dxdt_CENT =  KA * GUT - (CLi / Vi) * CENT;
# dxdt_R    =  KIN * (1 - INH) - KOUT * R;
# dxdt_p11  = -p11 * HAZ;
# 
# $CAPTURE CP HAZ
# '
# mod <- mcode("pkpd_hazard", code, quiet = TRUE)


## ----pkpd-simulate, eval=FALSE------------------------------------------------
# library(dplyr)
# library(survival)
# 
# set.seed(20260714)
# n         <- 300
# data_full <- expand.ev(ID = 1:n, amt = 100, cmt = 1, ii = 1,
#                        addl = 23, time = 0)
# out_full  <- as.data.frame(mrgsim(mod, data = data_full,
#                                   end = 24, delta = 0.1))
# 
# sim_event <- sim_tte_df(out_full %>% select(ID, time, p11))
# mean(sim_event$sim_status)   # event rate before additional censoring


## ----pkpd-validate, eval=FALSE------------------------------------------------
# apply_censoring <- function(event_time, true_status, shape, scale) {
#   cens <- rweibull(length(event_time), shape = shape, scale = scale)
#   data.frame(
#     observed_time = pmin(event_time, cens),
#     status        = as.integer(true_status == 1 & event_time <= cens)
#   )
# }
# 
# cohort    <- apply_censoring(sim_event$sim_time, sim_event$sim_status,
#                               shape = 1.5, scale = 20)
# fit_km    <- survfit(Surv(cohort$observed_time, cohort$status) ~ 1)
# mean_p11  <- out_full %>% group_by(time) %>%
#              summarise(mean_p11 = mean(p11), .groups = "drop")
# 
# plot(fit_km, col = "#CC3333", lwd = 2, conf.int = FALSE,
#      xlab = "Time (days)", ylab = "Survival probability",
#      main = "Simulated KM vs. population-average p11")
# lines(mean_p11$time, mean_p11$mean_p11, col = "black", lwd = 2, lty = 2)
# legend("topright",
#        legend = c("KM (simulated, censored)", "Mean p11 (ODE)"),
#        col = c("#CC3333", "black"), lwd = 2, lty = c(1, 2), bty = "n")


## ----pkpd-ic50, eval=FALSE----------------------------------------------------
# for (ic50 in c(0.3, 1.0, 5.0)) {
#   out_x <- as.data.frame(mrgsim(mod, data = data_full,
#                                 end = 24, delta = 0.1,
#                                 param = list(IC50 = ic50)))
#   sim_x <- sim_tte_df(out_x %>% select(ID, time, p11))
#   cat("IC50 =", ic50, "-> event rate =",
#       round(mean(sim_x$sim_status), 3), "\n")
# }
# # IC50 = 0.3  -> event rate = 0.503
# # IC50 = 1.0  -> event rate = 0.560
# # IC50 = 5.0  -> event rate = 0.727


## ----random-cens--------------------------------------------------------------
set.seed(1)
# event_time and true_status are from sim_tte() or sim_tte_df()
cens_time     <- rweibull(nrow(result), shape = 1.5, scale = 30)
observed_time <- pmin(result$sim_time, cens_time)
status        <- as.integer(result$sim_time <= cens_time &
                              result$sim_status == 1)

