# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit smitte.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(simtte)

