#' simtte: Simulate Time-to-Event Data from PK/PD and Bespoke ODE Models
#'
#' \if{html}{\figure{logo.png}{options: style='float: right' alt='logo' width=120}}
#'
#' Simulates time-to-event (survival) datasets for clinical trial design
#' and analysis, including datasets driven by a joint
#' pharmacokinetic/pharmacodynamic (PK/PD) model solved via the
#' \pkg{mrgsolve} backend.
#'
#' @section Joint PK/PD and time-to-event simulation:
#' \code{\link{sim_tte_ode}} locates each subject's event time directly
#' during ODE integration ("in-solver" event detection): the survival
#' probability is added to a PK/PD model as one more ODE compartment,
#' \code{p11}, with \code{dxdt_p11 = -p11 * HAZ}, and the solver is
#' watched for the first internal evaluation at which \code{p11} falls
#' to or below a per-subject uniform draw. Six built-in library models
#' (\code{"pk_hazard"}, \code{"irm1_hazard"}--\code{"irm4_hazard"},
#' \code{"tmdd_hazard"}; \code{\link{sim_tte_ode_models}} lists all of
#' them) cover common PK/PD structures out of the box. See
#' \code{vignette("pkpd-time-to-event", package = "simtte")} for a full
#' walkthrough.
#'
#' @section Bring your own PK/PD model:
#' \code{\link{tte_model}} converts any user-supplied \pkg{mrgsolve}
#' model (one with an \code{$ODE}/\code{$DES} block) into one usable by
#' \code{\link{sim_tte_ode}} the same way as a built-in model, including
#' coexistence with a model's own declared \code{$OMEGA} block. See
#' \code{vignette("bring-your-own-model", package = "simtte")}.
#'
#' @section Covariates, the linear predictor, and between-subject variability:
#' \code{\link{sim_tte_ode}}'s \code{covariates}/\code{beta} (optionally
#' \code{formula}, built into a design matrix via
#' \code{\link[stats]{model.matrix}}) add a linear predictor
#' \code{lp(t) = X(t) \%*\% beta} to any model; \code{omega} adds
#' log-normal between-subject variability on a model's own structural
#' PK/PD parameters. See \code{vignette("pkpd-time-to-event", package =
#' "simtte")}.
#'
#' @section Bespoke parametric/flexible hazard simulation:
#' \code{\link{sim_tte}}/\code{\link{sim_tte_df}} are the original API: a
#' unified interface for closed-form Weibull and flexible M-spline
#' baseline hazards, plus a fully model-agnostic entry point
#' (\code{sim_tte_df()}) for any already-simulated \code{(ID, time,
#' p11)} trajectory from any source. Event times are generated by
#' inverse transform sampling from the resulting cumulative hazard
#' function (Bender et al. 2005), with an optional sub-grid refinement
#' (\code{event_time_method = "log_survival"}). See
#' \code{vignette("introduction", package = "simtte")}.
#'
#' @section Right censoring:
#' \code{\link{add_censoring}} adds a second, independent censoring
#' process to the output of any of the three simulation functions above:
#' a per-subject censoring time drawn from an exponential, Weibull,
#' uniform, lognormal, gamma, or user-supplied distribution, with the
#' observed time becoming \code{min(event time, censoring time,
#' administrative end)}. \code{\link{censoring_rate_for}} solves for the
#' distribution parameter giving a target censoring fraction;
#' \code{\link{draw_censoring_times}} draws from the same kind of spec
#' directly. \code{\link{sim_tte_ode}} also accepts a \code{censoring}
#' argument that applies this automatically, inside its own seeded draw.
#' See \code{vignette("censoring-and-assessment", package = "simtte")}.
#'
#' @section Interval censoring and visit schedules:
#' \code{\link{add_interval_censoring}} maps an already-simulated (and,
#' if applicable, already right-censored) outcome onto an interval
#' \code{(L, R]}, given a visit/assessment-time schedule --
#' \code{\link{visit_schedule}} builds one with fixed spacing and
#' optional per-subject jitter, \code{\link{thin_visits}} layers
#' non-informative missed visits/dropout on top, and
#' \code{\link{visit_schedule_informative}} layers a visit process that
#' reacts to the simulated outcome. \code{\link{sim_tte_ode}} also
#' accepts a \code{visits} argument that applies interval censoring
#' automatically, always after any \code{censoring}. See
#' \code{vignette("censoring-and-assessment", package = "simtte")}.
#'
#' @section Full \pkg{mrgsolve} import:
#' Not narrowed to \code{importFrom()}: \pkg{mrgsolve} defines several
#' of its own methods on base generics (\code{as.data.frame},
#' \code{as.matrix}, ...) via S4 \code{setMethod()}/\code{exportMethods()},
#' not plain S3 registration (confirmed directly: \code{mrgsims} is an
#' S4 class, and \code{as.data.frame.mrgsims} is not found by
#' \code{.S3methods()} even once \pkg{mrgsolve}'s namespace is loaded).
#' Narrowing this to \code{importFrom(mrgsolve, mread, mrgsim, ...)} was
#' tried and broke \code{as.data.frame(mrgsim(...))} dispatch under
#' \code{devtools::load_all()} (\code{.sim_surv_df()}'s own
#' \code{as.data.frame(out)} call, used by every \code{sim_tte()}/
#' \code{sim_tte_df()} call) -- a full \code{import()} is what makes a
#' dependency's S4 methods on base generics reliably dispatchable from
#' the importing package's own code, not just its exported function
#' names, so it is kept.
#'
#' @references
#' Bender R, Augustin T, Blettner M (2005). Generating survival times to
#' simulate Cox proportional hazards models. \emph{Statistics in
#' Medicine}, 24(11), 1713-1723. \doi{10.1002/sim.2059}
#'
#' Royston P, Parmar MKB (2002). Flexible parametric proportional-hazards
#' and proportional-odds models for censored survival data, with
#' application to prognostic modelling and estimation of treatment
#' effects. \emph{Statistics in Medicine}, 21(15), 2175-2197.
#' \doi{10.1002/sim.1203}
#'
#' @keywords internal
#' @aliases simtte-package
#' @import mrgsolve
#' @importFrom dplyr group_by group_split bind_rows mutate filter select
#' @importFrom dplyr distinct inner_join left_join ungroup tibble
#' @importFrom stats runif
"_PACKAGE"
